import Head from 'next/head'
import { useState, useEffect } from 'react'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PaginationPage from '../components/PaginationPage.js'
import {getItems} from '../utils.js'


export default function Home({ paginationObj}) { 

 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
<PaginationPage paginationObj={paginationObj} />
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const batch = 10
  const ordering={direction: "asc", field: "name"}
const data = await getItems(0, 10, ordering);
const items = data.nodes|| [];
const cursor = data.cursor || 0;
const complete = data.complete || false;


return {
props: { paginationObj: {items, ordering, filters: {color: "blue"}, cursor, complete, batch}, 
}
}
}
